### ISSUE TITLE
visual indicator of dreams i've already seen?

### ISSUE THREAD

**Issue by data-doge** [enspiral-cherubi/dREAM-cACHER_interface_1.0#10]
as a returning user interested in seeing dreams i haven't seen before, i'd like some visual indication of dreams i've already seen.

i imagine on the back-end, a `clicks` table would be created, to join `dreams` and `users`.

i imagine on the UI, dreams that a user has clicked will appear a different color or something. and, clicking a dream will create a new entry in the back-end's `clicks` table.

again, just my 2c -- u do u

**Comment by will-sklenars** [comment]
Yuuup I have been thinking the same thing. There needs to be some way of
marking where you have been. I think a default colour change would work
well.

Also, It could be cool to give users the option to choose what colour each
dream becomes after they have seen it. Like, it could have a default color
that it changes to after you have read it, but then also a 'mark this
dream' option where you can make a dream bright green so that you can find
it later.

**Comment by will-sklenars** [comment]
The difficult bit might be updating the material of a specific dream without re-rendering the whole dreamscape as all the geometries are merged into one 'master' geometry. It is possible to have a geometry with multiple materials however. So this could be a thing.

**Comment by will-sklenars** [comment]
First iteration is  #23

**Comment by data-doge** [comment]
https://github.com/enspiral-cherubi/dREAM-cACHER_interface_1.0/pull/23
https://github.com/enspiral-cherubi/dREAM-cACHER/pull/5

merged, closing
