### ISSUE TITLE
fly controls shouldn't move user forward on click

### ISSUE THREAD

**Issue by data-doge** [enspiral-cherubi/dREAM-cACHER_interface_1.0#19]

**Comment by will-sklenars** [comment]
I see that in the current release of dream-cacher, this was achieved by commenting out lines 266 and 268 of flycontrols.js. 
// this.domElement.addEventListener( 'mousedown', bind( this, this.mousedown ), false );
// this.domElement.addEventListener( 'mouseup',   bind( this, this.mouseup ), false );

If we wanted to do this, we might have to make our own flycontrols node modual.

another option is If we use an empty div as 'domelement' on fly controls init. this stops all mouse events from working.

Maybe this is a good time to decide if we want to have the mouse control direction of the camera and just rely on arrow keys, or if we want to keep using the mouse. I feel that using the mouse is a pleasant way to navigate, but is annoying when trying to click on a dream, as it  means that the user has to position the camera so that the dream is in the middle of the screen. Otherwise, if you try and click on a dream that is off-centre, the camera starts moving. This feels not entirely intuitive. It may make for a more intuitive experience to make mouse just for clicking on dreams, and arrows for turning. What do you think?

**Comment by will-sklenars** [comment]
Also, I tried redefining controls.mousedown and controls.mouseup in environment.js, but in controls.js, these functions at some point are assigned to variables before being passed to the event listeners, which I think means that redefining them has no effect.

**Comment by will-sklenars** [comment]
I have made a branch for this fix, currently has no changes https://github.com/enspiral-cherubi/dREAM-cACHER_interface_1.0/tree/bug/controls-move-forward-on-click

**Comment by data-doge** [comment]
ya i like the mouse as a way of movin around -- also agree that clicking on dreams is too hard this way

ya actually arrow keys might feel really good

can you make a PR for it?

**Comment by data-doge** [comment]
possible soln in https://github.com/enspiral-cherubi/dREAM-cACHER_interface_1.0/pull/27

**Comment by will-sklenars** [comment]
Nice work
